### ISSUE TITLE
Error in the program

### ISSUE THREAD

**Issue by Yogapriya17** [pradeepkumar24rk/ZOHO-interview-Questions#4]
25: main()
{
    int i=0;
    switch(i)
    {
        case 0: i++;
                printf("%d", i);
        case 1:
                printf("%d", i);
        case 2:
                printf("%d", i);
    }
}
```
Output: `112`
 
initially, i=0 case 0; increments (i) to 1 and prints i, after there is no break statement 
control flows to case1: it prints 1 case 2: also get executed it prints 1.
So, the output is '111' .


28. main()
{
    int x=0;
    if(x=0)
        printf("value of x is zero");
    else
        printf("value of x is not zero");
}
```
Output: `value of x is zero`

Explanation: `if(x=0)` assigns `0` to `x`, which is `false`. Thus, `printf("value of x is zero");` gets executed. 

if(x=0) this block assigns 0 to x which is false then else block will get executed. the output is "value of x is not zero"  

35. int main()
{
    printf("%c", 5["welcomeall"]);
}
```
Output: `a`

Explanation: Equivalent to `printf("%c", "welcomeall"[5]);` 

5th character in welcomeall is 'm' 
correct me if I am wrong.....!😇

**Comment by pradeepkumar24rk** [comment]
Thank you for pointing out these issues! 

- **25:** Your solution is correct.  
- **28:** The provided solution is incorrect because the `if` statement only accepts a boolean value.  
- **35:** Your solution is correct.  

I will update the solution accordingly.
